lab-6_Rod/app/auth.py
from flask import Blueprint, render_template, redirect, url_for, flash, request
from flask_login import LoginManager, login_user, logout_user, login_required

from app.models import db
from app.repositories import UserRepository

user_repository = UserRepository(db)

bp = Blueprint('auth', __name__, url_prefix='/auth')

def init_login_manager(app):
    login_manager = LoginManager()
    login_manager.login_view = 'auth.login'
    login_manager.login_message = 'Для доступа к данной странице необходимо пройти процедуру аутентификации.'
    login_manager.login_message_category = 'warning'
    login_manager.user_loader(load_user)
    login_manager.init_app(app)

def load_user(user_id):
    return user_repository.get_user_by_id(user_id)

@bp.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        login = request.form.get('login')
        password = request.form.get('password')
        if login and password:
            user = user_repository.get_user_by_login(login)
            if user and user.check_password(password):
                login_user(user)
                flash('Вы успешно аутентифицированы.', 'success')
                next = request.args.get('next')
                return redirect(next or url_for('main.index'))
        flash('Введены неверные логин и/или пароль.', 'danger')
    return render_template('auth/login.html')

@bp.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('main.index'))

lab-6_Rod/app/templates/base.html
<!doctype html>
<html lang="ru" class="h-100">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">

    <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">

    <title>Образовательный портал | Московский Политех</title>
</head>

<body class="d-flex flex-column h-100">
    <header>
        <nav class="navbar navbar-dark bg-dark">
            <div class="container-fluid">
                <div class="logo navbar-brand">
                    <a href="{{ url_for('main.index') }}">
                        <img class="img-fluid" src="{{ url_for('static', filename='images/polytech_logo.png') }}" alt="polytech-logo">
                    </a>
                </div>
                {% if current_user.is_authenticated %}
                    <div class="dropdown d-flex" style="width: 200px;">
                        <div class="profile ms-auto" title="{{ current_user.full_name }}" id="dropdownMenuButton" data-bs-toggle="dropdown"
                            aria-haspopup="true" aria-expanded="false">
                            <img class="img-fluid rounded-circle cursor-pointer"
                                src="{{ url_for('static', filename='images/default-profile-picture-300x300.jpeg') }}" alt="profile-pic">
                        </div>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                            <a class="dropdown-item" href="#">Профиль</a>
                            <a class="dropdown-item" href="#">Мои курсы</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{{ url_for('auth.logout') }}">Выйти</a>
                        </div>
                    </div>
                {% else %}
                    <a class="btn btn-outline-light" href="{{ url_for('auth.login') }}">Войти</a>
                {% endif %}
            </div>
        </nav>
    </header>
        
    <div class="alerts-area">
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% for category, msg in messages %}
                <div class="alert alert-{{ category }} alert-dismissible fade show m-0 rounded-0" role="alert">
                    {{ msg }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            {% endfor %}
        {% endwith %}
    </div>

    <main class="main flex-grow-1">
       {% block content %}
       {% endblock %}
    </main>

    <footer class="bg-dark text-white d-flex align-items-center justify-content-center py-3">
        &copy; Московский политехнический университет
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2"
        crossorigin="anonymous"></script>

    <script defer src="{{ url_for('static', filename='main.js') }}"></script>
</body>

</html>

lab-6_Rod/app/templates/index.html
{% extends 'base.html' %}

{% block content %}
<div class="h-100 text-center d-flex p-3 bg-light">
    <div class="m-auto">
        <h1 class="title mb-5 font-weight-bold">Образовательный портал</h1>
        
        <div class="container">
            <p class="description w-75 mb-5 px-3 mx-auto">
                Мы создаем и продвигаем технологии онлайн-образования как эффективный 
                образовательный инструмент, который будет способствовать повышению 
                доступности и качества образования.
            </p>

            <div class="my-5 p-3 bg-dark rounded">
                <form action="{{ url_for('courses.index') }}" class="row align-items-center">
                    <div class="col-sm-12 mb-3 col-md-6 mb-md-0">
                        <input autocomplete="off" type="text" class="form-control" id="course-name" name="name" placeholder="Название курса">
                    </div>
                    
                    <div class="col-sm-12 mb-3 col-md-4 mb-md-0">
                        <select class="form-select" id="course-category" name="category_ids" title="Категория курса">
                            <option value="">Выберите категорию</option>
                            {% for category in categories %}
                                <option value="{{ category.id }}">{{ category.name }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    
                    <div class="col-sm-12 col-md-2 align-self-end">
                        <button type="submit" class="btn btn-outline-light w-100 mt-auto">Найти</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

lab-6_Rod/app/templates/pagination.html
{% macro render_pagination(pagination, endpoint, params={}) %}
    {% set per_page = pagination.per_page %}
    <nav>
        <ul class="pagination justify-content-center">
            <li class="page-item {% if not pagination.has_prev %}disabled{% endif %}">
                <a class="page-link" href="{{ url_for(endpoint, page=(pagination.page - 1), per_page=per_page, **params) if pagination.has_prev else '#' }}" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
            {%- for page in pagination.iter_pages() %}
                {% if page %}
                    <li class="page-item {% if page == pagination.page %}active{% endif %}">
                        <a class="page-link" href="{{ url_for(endpoint, page=page, per_page=per_page, **params) }}">
                            {{ page }}
                        </a>
                    </li>
                {% endif %}
            {%- endfor %}
            <li class="page-item {% if not pagination.has_next %}disabled{% endif %}">
                <a class="page-link" href="{{ url_for(endpoint, page=(pagination.page + 1), per_page=per_page, **params) if pagination.has_next else '#' }}" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
        </ul>
    </nav>
{% endmacro %}